---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-authorized-keys
    image: geerlingguy/docker-ubuntu1804-ansible
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    v: false
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
